CREATE TABLE USUARIO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DNI VARCHAR(10) NOT NULL,
    NAME VARCHAR NOT NULL,
    APELLIDO1 VARCHAR NOT NULL,
    APELLIDO2 VARCHAR,
    FECHA_NAC DATETIME NOT NULL,
    EDAD INT,
    EMAIL VARCHAR NOT NULL,
    PASS VARCHAR NOT NULL,
    DIRECCION INT
);

CREATE TABLE RESTAURANTE (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR NOT NULL,
    EMPRESA_ENVIO_PROPIA BOOLEAN NOT NULL
)

CREATE TABLE DIRECCION (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    LOCALIDAD VARCHAR NOT NULL,
    CP INT NOT NULL,
    DIRECCION VARCHAR NOT NULL
);

CREATE TABLE PLATO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    REFERENCIA VARCHAR NOT NULL,
    NOMBRE VARCHAR NOT NULL,
    PRECIO_UNITARIO DOUBLE
);

